# Generated by Django 4.0.4 on 2022-06-02 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('price', models.JSONField(default={0: 10, 1: 100, 2: 1000, 3: -1})),
                ('buyable', models.BooleanField(default=False)),
                ('cur_price', models.IntegerField(default=10)),
                ('auto_click_intervals', models.JSONField(default={0: -1, 1: 10000, 2: 5000, 3: 1000})),
                ('cur_interval', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='StrBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('price', models.JSONField(default={0: 10, 1: 100, 2: 1000, 3: -1})),
                ('buyable', models.BooleanField(default=False)),
                ('cur_price', models.IntegerField(default=10)),
                ('powers', models.JSONField(default={0: 0, 1: 1, 2: 5, 3: 10})),
                ('cur_power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('click_power', models.IntegerField(default=1)),
                ('int_boosts', models.ManyToManyField(to='backend.intboost')),
                ('str_boosts', models.ManyToManyField(to='backend.strboost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
