# Generated by Django 4.0.4 on 2022-05-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=10)),
                ('buyable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntBoost',
            fields=[
                ('boost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.boost')),
            ],
            bases=('backend.boost',),
        ),
        migrations.CreateModel(
            name='StrBoost',
            fields=[
                ('boost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.boost')),
            ],
            bases=('backend.boost',),
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('click_power', models.IntegerField(default=1)),
                ('auto_click_interval', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('int_boost', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.intboost')),
                ('str_boost', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.strboost')),
            ],
        ),
    ]
