# Generated by Django 4.0.4 on 2022-06-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strboost',
            name='description',
            field=models.TextField(default='Описание буста'),
        ),
        migrations.AddField(
            model_name='strboost',
            name='name',
            field=models.TextField(default='Имя буста'),
        ),
    ]
