# Generated by Django 4.0.4 on 2022-06-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_intboost_description_intboost_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='intboost',
            name='cur_level_name',
            field=models.TextField(default='ноль'),
        ),
        migrations.AddField(
            model_name='intboost',
            name='level_names',
            field=models.JSONField(default={0: 'ноль', 1: 'один', 2: 'два', 3: 'три'}),
        ),
        migrations.AddField(
            model_name='strboost',
            name='cur_level_name',
            field=models.TextField(default='ноль'),
        ),
        migrations.AddField(
            model_name='strboost',
            name='level_names',
            field=models.JSONField(default={0: 'ноль', 1: 'один', 2: 'два', 3: 'три'}),
        ),
    ]
